housingsociety/user/forms.py
from wtforms import StringField, PasswordField, RadioField, SubmitField, DateField, FloatField, DecimalField, IntegerField, FieldList, FormField, HiddenField, SelectMultipleField
from wtforms.widgets import TextArea, CheckboxInput, ListWidget
from wtforms import validators
from wtforms.validators import DataRequired, Optional
from flask_wtf import Form, FlaskForm

class AddBillForm(FlaskForm):
	billDate      = DateField('Bill Date', format='%Y-%m-%d', validators=[DataRequired()])
	dueDate       = DateField('Due Date',  format='%Y-%m-%d', validators=[DataRequired()])
	selectedWings = SelectMultipleField('Wings', choices=[],widget=ListWidget(prefix_label=False),option_widget=CheckboxInput(), validators=[DataRequired()])
	WATER_CHARGES		=DecimalField(label='WATER CHARGES'       ,places=2, validators=[DataRequired()])
	PROPERTY_TAX		=DecimalField(label='PROPERTY TAX'        ,places=2, validators=[DataRequired()])
	ELECTRICITY_CHARGES=DecimalField(label='ELECTRICITY CHARGES',places=2, validators=[DataRequired()])
	SINKING_FUNDS		=DecimalField(label='SINKING FUNDS'       ,places=2, validators=[DataRequired()])
	PARKING_CHARGES		=DecimalField(label='PARKING CHARGES'     ,places=2, validators=[DataRequired()])
	INSURANCE			=DecimalField(label='INSURANCE' ,places=2, validators=[DataRequired()])
	OTHER				=DecimalField(label='OTHER'     ,places=2, validators=[Optional()])
	submitBtn = SubmitField(label='Submit')

housingsociety/user/views.py
from flask import Blueprint
from housingsociety.models import Member
from flask import Flask,render_template,request,url_for,redirect, session,flash,make_response
import random
import re
import smtplib
from housingsociety import db, mail
from housingsociety.models import Notice,Paydetails,Complaint
import pdfkit
from datetime import date
from flask_mail import Message
from flask_mail import Mail

userlogin_blueprint = Blueprint('userlogin',__name__)
@userlogin_blueprint.route('/',methods = ['GET', 'POST'])
def home():
    return render_template('user/ahome.html')

@userlogin_blueprint.route('/loginuser',methods = ['GET', 'POST'])
def user_login():
    msg= None
    if request.method == 'POST': 
        email = request.form["email"]
        password = request.form["password"]
        login = Member.query.filter_by(email=email,password=password).first()
        if login:
            session['flat_num'] = login.flatno
            session['user_name'] = login.name
            session['email'] = login.email

            return redirect(url_for("userlogin.home"))
        else:
             msg = 'Invalid User'
    return render_template('user/login.html',msg = msg)

@userlogin_blueprint.route('/logoutuser')
def logout():
    session.pop('flat_num', None)
    return render_template('user/ahome.html')


@userlogin_blueprint.route('/noticeview')
def getnotice():
    unote = Notice.query.all()
    return render_template('user/viewnotice.html',unote=unote)

@userlogin_blueprint.route('/viewdetail/<id>/')
def viewnotice(id):
    unote = Notice.query.get(id)
    return render_template('user/viewnotice.html',unote=unote)
   
@userlogin_blueprint.route('/downloadpdf',methods = ['GET', 'POST'])
def noticepdf():
    notepdf = Notice.query.get(request.form.get('id'))
    html = render_template("user/notice_details_pdf.html",notepdf=notepdf)
    config = pdfkit.configuration(wkhtmltopdf=r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe")
    pdf = pdfkit.from_string(html, False,configuration=config)
    response = make_response(pdf)
    response.headers["Content-Type"] = "application/pdf"
    response.headers["Content-Disposition"] = "inline; filename=notice.pdf"
    return response

@userlogin_blueprint.route('/complaint',methods = ['GET', 'POST'])
def complaint():
    msg = ''
    if request.method=='POST':
        name = request.form.get('name')
        email = request.form.get('email')
        subject = request.form.get('subject')
        message = request.form.get('message')
        flatno_id =  session.get('flat_num')
        complaintdate = date.today()
        if not name  or not subject or not message or not email:
            msg = 'Please fill out the form !'
        elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
            msg = 'Invalid email address !'
        else:
            if flatno_id:
                entry = Complaint(name=name,email=email,complaintdate=complaintdate,flatno_id=flatno_id,subject=subject,message=message)
                db.session.add(entry)
                db.session.commit()
                message1 = "Received your complaint. We will soon take soon action. Thank you."
                server = smtplib.SMTP("smtp.gmail.com",587)
                server.starttls()
                server.login("djangopro3031@gmail.com","fustntwudpvnbqaw")
                server.sendmail("djangopro3031@gmail.com", email, message1)
    return render_template('user/complaint.html',msg = msg)

@userlogin_blueprint.route('/changepassword',methods = ['GET', 'POST'])
def changepassword():
    msg= None
    smsg= None
    if request.method == 'POST': 
        flatno =  session.get('flat_num')
        my_data = Member.query.filter_by(flatno = flatno).first()
        if flatno :
            newpassword = request.form['rpass']
            compassword = request.form['crpass']
            if newpassword != compassword:
                msg='password doesnt match'
            else:
                my_data.password = newpassword
                db.session.commit()
                smsg = 'password change'
    return render_template('user/resetpass.html',msg=msg,smsg=smsg)
   
def sendmail(flatno):
    token = flatno.get_reset_token()
    msg = Message('Password Reset Request',
                  sender='noreply@demo.com',
                  recipients=[flatno.email])
    msg.body = f'''To reset your password, visit the following link:
                {url_for('userlogin.reset_token', token=token, _external=True)}
                        If you did not make this request then simply ignore this email and no changes will be made.
                        '''
    mail.send(msg)

@userlogin_blueprint.route('/reset',methods = ['GET', 'POST'])
def resetpassword():
    msg= None
    if request.method == 'POST': 
        email = request.form["email"]
        flatno  = Member.query.filter_by(email=email).first()
        if flatno :
            sendmail( flatno )
            msg = 'Please Check Your Email To reset Your Paasword'
    return render_template('user/reset_password.html',msg=msg)

@userlogin_blueprint.route('/reset/<token>',methods = ['GET', 'POST'])
def reset_token(token):
    flatno = Member.verify_reset_token(token)
    if flatno is None:
        flash('that is invaild token')
        return redirect(url_for('userlogin.resetpassword'))
    if request.method == 'POST': 
        flatno.password = request.form['password']
        db.session.commit()
        return redirect(url_for('userlogin.user_login'))
    return render_template('user/changepassword.html')

housingsociety/templates/user/ahome.html
{% extends "user/base.html" %}

{% block body %}
  <!-- ======= Hero Section ======= -->
  <section id="hero" >
    <div class="hero-container" data-aos="fade-up">
    </br></br>
      <h1>Welcome!</h1>
      <h2>Let's go green, go online with arpita housing society.</h2>
    </div>
  </section><!-- End Hero -->

  <!-- Vendor JS Files -->
  <script src="{{ url_for('static',filename='userhome/assets/vendor/aos/aos.js')}}"></script>
  <script src="{{ url_for('static',filename='userhome/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{ url_for('static',filename='userhome/assets/vendor/glightbox/js/glightbox.min.js')}}"></script>
  <script src="{{ url_for('static',filename='userhome/assets/vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
  <script src="{{ url_for('static',filename='userhome/assets/vendor/php-email-form/validate.js')}}"></script>
  <script src="{{ url_for('static',filename='userhome/assets/vendor/purecounter/purecounter.js')}}"></script>
  <script src="{{ url_for('static',filename='userhome/assets/vendor/swiper/swiper-bundle.min.js')}}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static',filename='userhome/assets/js/main.js')}}"></script>

{% endblock %}

housingsociety/templates/user/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Arpita Housing Society</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static',filename='userhome/assets/vendor/aos/aos.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='userhome/assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='userhome/assets/vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='userhome/assets/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='userhome/assets/vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static',filename='userhome/assets/vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ url_for('static',filename='userhome/assets/css/style.css')}}" rel="stylesheet">
{% block css %} {% endblock %}
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">
    <div class="logo">
        <h1 class="text-light"><span></span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          {% if session.flat_num %}
          <li><a class="nav-link scrollto" href="/noticeview">NoticeBoard</a></li>
          <li><a class="nav-link scrollto" href="/complaint">Complaint</a></li>
          <li><a class="nav-link scrollto" href="/MainBill">Maintainance</a></li>
           <li class="dropdown"><a href="#"><span>Account</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="/uhistory">Payment History</a></li>
              <li><a href="/changepassword">Change Password</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="/logoutuser">Logout</a></li>
          <li><b>Hello,{{session.user_name}}</b></li>
           {% else %}
           <li class="dropdown"><a href="#"><span>Login</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="/loginuser">Member</a></li>
              <li><a href="/adminlogin">Admin</a></li>
            </ul>
          <li><b>Hello,User</b></li>
          </li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
  {% block body %} {% endblock %}
  </body>
  </html>

housingsociety/templates/user/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{{ url_for('static',filename='userlogin/images/icons/favicon.ico')}}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='userlogin/vendor/bootstrap/css/bootstrap.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='userlogin/fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='userlogin/fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='userlogin/vendor/animate/animate.css')}}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='userlogin/vendor/css-hamburgers/hamburgers.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='userlogin/vendor/select2/select2.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='userlogin/css/util.css')}}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='userlogin/css/main.css')}}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('static/userlogin/images/img-01.jpg');">
			<div class="wrap-login100 p-t-190 p-b-30">
				<form class="login100-form validate-form"   method="POST">
					
					<span class="login100-form-title p-t-20 p-b-45">
						Welcome, User!
					</span>

					<div class="wrap-input100 validate-input m-b-10" data-validate = "Email is required">
						<input class="input100" type="password" name="password" placeholder="newpassword">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input m-b-10" data-validate = "Password is required">
						<input class="input100" type="password" name="cpassword"   placeholder="confirmpassword">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock"></i>
						</span>
					</div>

					<div class="container-login100-form-btn p-t-10">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
					{% if msg %}
        			<p class="alert alert-danger alert-dismissible fade show"><strong>Error:</strong> {{ msg }}
      			{% endif %}
				</form>
				
			</div>
		</div>
	</div>	
<!--===============================================================================================-->	
	<script src="{{ url_for('static',filename='userlogin/vendor/jquery/jquery-3.2.1.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static',filename='userlogin/vendor/bootstrap/js/popper.js')}}"></script>
	<script src="{{ url_for('static',filename='userlogin/vendor/bootstrap/js/bootstrap.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static',filename='userlogin/vendor/select2/select2.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for('static',filename='userlogin/js/main.js')}}"></script>

</body>
</html>

housingsociety/templates/user/complaint.html
{% extends "user/base.html" %}
	{% block css %}
   {{ super() }}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,700,900&display=swap" rel="stylesheet">

    
    
    
    <!-- Style -->
    <link rel="stylesheet" href="{{ url_for('static',filename='complaint/css/style.css')}}">

    <title>Complaint</title>
{% endblock  %}
{% block body %}

  <div class="content">
    
    <div class="container">

      
      <div class="row justify-content-center">
        <div class="col-md-10">
          
          <div class="row align-items-center">
            <div class="col-lg-7 mb-5 mb-lg-0">

              <h2 class="mb-5">Fill the form. <br> It's easy.</h2>

              <form class="border-right pr-5 mb-5" method="POST" action="{{url_for('userlogin.complaint')}}" >
                <div class="row">
                  <div class="col-md-12 form-group">
                    <input type="text" class="form-control" name="name" id="name" placeholder="Enter your name">
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12 form-group">
                    <input type="text" class="form-control" name="email" id="email" placeholder="Enter your EmailID">
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12 form-group">
                    <input type="text" class="form-control" name="subject" id="subject" placeholder="Enter your subject">
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-12 form-group">
                    <textarea class="form-control" name="message" id="message" cols="30" rows="7" placeholder="Write your message"></textarea>
                  </div>
                </div>
                <br/>
                <div class="row">
                  <div class="col-md-12">
                    <input type="submit" value="Send Message" class="btn btn-primary rounded-0 py-2 px-4">
                    <span class="submitting"></span>
                  </div>
                </div>
              </form>


            </div>
            <div class="col-lg-4 ml-auto">
              <h3 class="mb-4">Let's talk about everything.</h3>
              <p>We are here to help you out with all your issues. Feel free to put your complaints.</p>
            </div>
          </div>
        </div>  
        </div>
      </div>
  </div>
    
    

    <script src="{{ url_for('static',filename='complaint/js/jquery-3.3.1.min.js')}}"></script>
    <script src="{{ url_for('static',filename='complaint/js/popper.min.js')}}"></script>
    <script src="{{ url_for('static',filename='complaint/js/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static',filename='complaint/js/jquery.validate.min.js')}}"></script>
    <script src="{{ url_for('static',filename='complaint/js/main.js')}}"></script>
{% endblock  %}

housingsociety/templates/user/issues.html
{% extends "user/base.html" %}

<form id="fs-frm" name="complaint-form" accept-charset="utf-8" action="https://formspree.io/f/{form_id}" method="post">
  <fieldset id="fs-frm-inputs">
    <label for="full-name">Full Name</label>
      <input type="text" name="name" id="full-name" placeholder="First and Last" required="">
    <label for="email-address">Email Address</label>
      <input type="email" name="_replyto" id="email-address" placeholder="email@domain.tld" required="">
    <label for="telephone">Telephone Number (Optional)</label>
      <input type="telephone" name="telephone" id="telephone" placeholder="(555) 555-5555">
    <label for="complaint">Complaint</label>
      <textarea rows="6" name="complaint" id="complaint" placeholder="Aenean lacinia bibendum nulla sed consectetur. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla nullam quis risus." required=""></textarea>
    <input type="hidden" name="_subject" id="email-subject" value="Complaint Form Submission">
  </fieldset>
  <input type="submit" value="File Complaint">
</form>

housingsociety/templates/user/maintaince.html
{% extends "user/base.html" %}
	{% block css %}
   {{ super() }}
{% endblock  %}
{% block body %}
<br> <br> <br> <br> <br> <br> 
<div class="col-md-10">
	<div class="container currBillContainer">
	
		
		 {% if details %}
		 {% for row in details %}
		 <table class="table table-bordered">
  			<h1  class="float-left" style="color: #6b6b47;">Maintainence Bill</h1>
			<h4  class="float-md-right" id="billDate">Date : <span id="date">{{ row.bill_date }}</span></h4>
			<h4  class="float-md-right" id="billDate">Due Date : <span id="date">{{ row.due_date }}</span></h4>
		
			<thead class="thead-dark">
				<tr>
					<th>Category</th>
					<th>Cost</th>
				</tr>
			</thead>
			<tbody style="text-transform: capitalize;">
			 
				<tr>
					<td>Water Charges</td>
					<td>{{ row.water_charges }}</td>
				</tr>
        <tr>
					<td>Property Tax</td>
					<td>{{ row.property_tax }}</td>
				</tr>
        <tr>
					<td>Electrical Charges</td>
					<td>{{ row.elec_charges }}</td>
				</tr>
        <tr>
					<td>Sinking Funds</td>
					<td>{{ row.sinking_fund }}</td>
				</tr>
        <tr>
					<td>Parking Charges</td>
					<td>{{ row.parking_charges }}</td>
				</tr>
        <tr>
					<td>Other Charges</td>
					<td>{{ row.other }}</td>
				</tr>
				{% endfor %}
					
				<tr class="table-active">
					<td>Total</td>
					<td>{{totalsum}}</td>
				</tr>
			</tbody>
 		</table>
		 <div class="text-center align-middle">
    				<div class="btn-group">
        				<a href="/Payment" button class="btn btn-outline-primary">Payment</a></button>
    				</div>                
				</div>
	</div>
	<script>
							  {% if msg%}
								
							swal('{{ msg }}');
							{% endif %}
					</script>
		
		{% else %}

	<h1 class="float-left" align="center" style="color: #6b6b47;">No Bill</h1>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	{% endif %}
{% endblock %}

housingsociety/templates/user/notice_details_pdf.html
<!DOCTYPE html>
<html>
<head>
    <title>Notice</title>
    <style>
        table {
            width: 100%;
        }
        table, th, td {
            border: solid 1px #DDD;
            border-collapse: collapse;
            padding: 2px 3px;
            text-align: left;
            font-family:Arial, Helvetica, sans-serif;
            height: 50px;
            vertical-align: bottom;
        }
        .signature { 
            display: inline; 
            width: 30%;
            }
    </style>
</head>
<body>
<br/>
 <h1>Arpita Housing Society</h1>
 <hr><br/>
    <p style="font-size:200%;"><b>Date:</b> {{notepdf.date}}</p>
    <p style="font-size:200%;"><b>Subject:</b> {{notepdf.subject}} </p>
    <p style="font-size:200%;"><b>Description:</b> {{notepdf.description}} </p>
    <br/><hr>
    <div align="right" class="signature">
        <h2>Secretary's Sign:</h2>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Jon_Kirsch%27s_Signature.png/320px-Jon_Kirsch%27s_Signature.png" align="right"/>
    </div>

</body>
</html>

housingsociety/templates/user/paymenthistory.html
{% extends "user/base.html" %}
	{% block css %}
   {{ super() }}
<style>
#customers {
    margin-left: auto;
    margin-right: auto;
    font-family: Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 80%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: Plum;
  color: white;
}
</style>
{% endblock  %}
{% block body %}
<br/><br/><br/><br/><br/><br/>
<table id="customers">
  <tr>
    <th>Name</th>
    <th>Flat No</th>
    <th>Amount</th>
     <th>Payment date</th>
     <th>Receipt</th>
  </tr>
  {% for sts in st %}
  <tr>
   <td>{{sts.name}}</td>
      <td> {{sts.flatno_id}}</td>
      <td>{{sts.amount}}</td>
      <td>{{sts.paydate}}</td>
      <td><a href="/downloadinvoice/{{sts.pay_id}}"class="btn btn-success"type="submit">Download</a></td>

   </tr>
   {% endfor %} 
</table>
{% endblock  %}

housingsociety/templates/user/resetpass.html
{% extends "user/base.html" %}
 {% block css %}
   {{ super() }}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static',filename='reset/css/style.css')}}">
    {% endblock %}
    {% block body %}
    <br/><br/><br/><br/><br/>
    <div class="registration-form">
        <form  method="POST"  action="{{url_for('userlogin.changepassword')}}">
        
            <div class="form-icon">
                <span><i class="icon icon-user"></i></span>
            </div>
            <div class="form-group">
                <input type="password" class="form-control item" name="rpass" placeholder="New Password">
            </div>
            <div class="form-group">
                <input type="password" class="form-control item" name="crpass" placeholder="Confirm New Password">
            </div>
            <div class="form-group">
            
                <button type="submit" class="btn btn-block create-account">Reset</button>
            </div>
            {% if msg %}
        			<p class="alert alert-danger"><strong>Error:</strong> {{ msg }}
      		{% endif %}
            {% if smsg %}
        			<p class="alert alert-success"><strong>Success:</strong> {{ smsg }}
      		{% endif %}
        </form>
    
    </div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    <script src="{{ url_for('static',filename='reset//js/script.js')}}"></script>

 {% endblock %}

housingsociety/templates/user/viewnotice.html
{% extends "user/base.html" %}
	{% block css %}
   {{ super() }}
	<script type="text/javascript" src={{ url_for('static',filename='unotice/lib/jquery.js')}}></script>
	<script type="text/javascript" src={{ url_for('static',filename='unotice/lib/Chart.bundle.js')}}></script>
	<style>
	.padding{
		position: center;
		align: center;
		margin-left: 30px;
	}
	</style>
{% endblock  %}
{% block body %}
<br> <br> <br> <br> <br> <br> 
<div class="col-md-4 table-div" align="center">
<div class="padding">
	<div id="scrollDiv" align="center">
		<table class="table table-hover table-striped">
			<thead>
				<tr class="table-primary text-gray-dark" style="font-size: 1.5em; color: #004d99;">
					<th>Subject</th>
					<th>Date</th>
					<th>View Notice</th>
				</tr>
			</thead>
			<tbody id="notifBody">
			 {% for unote in unote %}
                    <tr>
                        <td>{{unote.subject}}</td>
                        <td>{{unote.date}}</td>
					<td><a href="/viewdetail/{{unote.id}}"class="btn btn-secondary" data-toggle="modal" data-target="#modalview{{unote.id}}" >View</a></td>	
    {% endfor %}
			</tbody>
		</table>
	</div>
	<a href="/noticeview"class="btn btn-warning btn-lg btn-block" id="refreshNotif" >Refresh</a>
</div> 
</div>
{% for unote in unote %}

<div class="modal fade" id="modalview{{unote.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Description</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  <form action="{{url_for('userlogin.noticepdf')}}" method="POST"> 
   			<input type="hidden"  name="id" value="{{unote.id}}">
				<div class="form-group">
				<label>{{unote.description}}</label>
				</div>
				<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button class="btn btn-primary" type="submit">Download</button>
			</div>
	</form>
 
      </div>
    </div>
	 
  </div>
</div>
 {% endfor %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock  %}